@token={{login.response.body.accessToken}}

# Login user by email and password
# @name login
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@test.local",
  "password": "123456"
}

###

# Get publication  by ID
GET http://localhost:3001/api/blog-list/53 HTTP/1.1

###


# Get all posts
GET http://localhost:3001/api/blog-list?limit=25&page=1&tag=tag2 HTTP/1.1

###

# Get all posts by name
GET http://localhost:3001/api/blog-list/search?title=small%20title  HTTP/1.1

###

# Get drafts
GET http://localhost:3001/api/blog-list/drafts  HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

###

# Send news
GET http://localhost:3001/api/blog-list/send-news HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

###
