# Upload post image
POST http://localhost:3333/api/file/post HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5ydSIsImlkIjoiNjQ5MDY2ZGE4NTZmMDE4MWNmMmI3ZGRlIiwiaWF0IjoxNjg3MzU4MDM2LCJleHAiOjE2ODc1MzA4MzZ9.DUnHw9jrZj3AqcJVzbeorJGoxHOWY5i48xLPZoa0CAk

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photos"; filename="room1.jpg"
Content-Type: image/jpeg

< ./static/room1.jpg

###

# Upload avatar image
POST http://localhost:3333/api/feed/7aef6925-4fe5-4057-b5cc-cc7cf214df05 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5ydSIsImlkIjoiNjQ5MDY2ZGE4NTZmMDE4MWNmMmI3ZGRlIiwiaWF0IjoxNjg3MzU4MDM2LCJleHAiOjE2ODc1MzA4MzZ9.DUnHw9jrZj3AqcJVzbeorJGoxHOWY5i48xLPZoa0CAk

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photos"; filename="room1.jpg"
Content-Type: image/jpeg

< ./static/room1.jpg

###

###
