# Create post
POST http://localhost:3001/api/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0OTA2MWE1OGZhNGIyZWVkZTJlZGE0ZCIsImlhdCI6MTY4Nzc5NTYxMywiZXhwIjoxNjg3OTY4NDEzfQ.oHuCNg3bL33T_WNiH8dSSpqk5_Qk9V0XrUXyGAi4nxE
Content-Type: application/json

{
  "title": "Title of the post",
  "tegs": ["#love"],
  "author": "3",
  "status": "published",
  "likesCount": 25,
  "isReposted": false,
  "originAuthor": "",
  "originId": "",
  "type": "photo",
  "photo": "/images/1.jpg"
}

###

# Update post by ID
PATCH http://localhost:3333/api/post/6485f358299152496b800a62 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0OTA2MWE1OGZhNGIyZWVkZTJlZGE0ZCIsImlhdCI6MTY4Nzc5NTYxMywiZXhwIjoxNjg3OTY4NDEzfQ.oHuCNg3bL33T_WNiH8dSSpqk5_Qk9V0XrUXyGAi4n
Content-Type: application/json

{
  "title": "The universe loves you",
  "tegs": ["#love", "universe"]
}

###

# Get post by ID
GET http://localhost:3000/api/post/1 HTTP/1.1

###

# Get all posts and filtres
GET http://localhost:3000/api/post?sortDirection=desc&limit=2&page=1 HTTP/1.1

###

# Get all posts
GET http://localhost:3000/api/post HTTP/1.1

###

# Delete post
DELETE  http://localhost:3000/api/post HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0OTA2MWE1OGZhNGIyZWVkZTJlZGE0ZCIsImlhdCI6MTY4Nzc5NTYxMywiZXhwIjoxNjg3OTY4NDEzfQ.oHuCNg3bL33T_WNiH8dSSpqk5_Qk9V0XrUXyGAi4nxE

###

# Get comments of the post
GET http://localhost:3000/api/post/6485f358299152496b800a62/comments HTTP/1.1

###

# Post new comment of the post
POST http://localhost:3333/api/post/6485f358299152496b800a62/comments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0OTA2MWE1OGZhNGIyZWVkZTJlZGE0ZCIsImlhdCI6MTY4Nzc5NTYxMywiZXhwIjoxNjg3OTY4NDEzfQ.oHuCNg3bL33T_WNiH8dSSpqk5_Qk9V0XrUXyGAi4nxE
Content-Type: application/json

{
  "text": "The universe loves you",
  "author": "6485f358299152496b800a62"
}
###

